# Generated by Django 3.1.2 on 2020-10-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_repair'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repair',
            new_name='WarrantyQuote',
        ),
    ]
