# Generated by Django 3.1.2 on 2020-10-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201011_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='remark',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='quote',
            name='type',
            field=models.CharField(default='purchase', max_length=100),
        ),
    ]
